spring:
  jackson:
    default-property-inclusion: non_null
  profiles:
    default: local

openapi:
  info:
    title: Reckful's Twitter Archive
    short-description: API endpoints for querying tweets of or related to Byron (Reckful) Bernstein.
    source-code-link: https://github.com/ReckfulArchive/twitter

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    default-models-expand-depth: 0
  disable-i18n: true
