server:
  port: 8080

openapi:
  serverUrls:
    - http://localhost:8080

importer:
  data:
    vicinitas:
      historical-tweets-tsv:
        - /home/ignat/IdeaProjects/twitter-data/data/vicinitas/historical-tweets-byron.tsv
      free-tweets-tsv:
        - /home/ignat/IdeaProjects/twitter-data/data/vicinitas/free-tweets-reckful.tsv
        - /home/ignat/IdeaProjects/twitter-data/data/vicinitas/free-tweets-playeverland.tsv
