spring:
  jackson:
    default-property-inclusion: non_null

springdoc:
  swagger-ui:
    path: /swagger-ui.html

importer:
  data:
    vicinitas:
      tweets-tsv: /home/ignat/IdeaProjects/twitter-data/data/vicinitas/tweets.tsv
