server:
  port: 9550

spring:
  jackson:
    default-property-inclusion: non_null

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    default-models-expand-depth: 0
  disable-i18n: true

importer:
  data:
    vicinitas:
      tweets-tsv: ~/twitter-data/data/vicinitas/tweets.tsv
